version: '3.9'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - server
      - django-app

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  django-app:
    build:
      context: ./django-app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./django-app:/app
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/karen_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  flask-microservice:
    build:
      context: ./flask-microservice
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./flask-microservice:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - server

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=karen_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: